export const portfolioGallery = [
    {
        id:1,
        title:"AI/ML",
        image:"/AI Metadata Hub.gif",
        category: "AI Metadata Hub",
        techStack: ["React", "TypeScript", "Fastify", "MongoDB", "Vertex AI", "Azure Doc Intelligence"],
        width: 450,
        height: 350,
        path: "AI-ML/AIMetadataHub",
        description: "AI-Powered Document Management Platform for PETRONAS that automates document classification and metadata extraction with 100% accuracy, reducing manual work from years to hours.",
        demoLink: "https://consurv.axtraction.fyi/",
    },
    {
        id:2,
        title:"MobileApps",
        image:"/Smart Move Vid.gif",
        category: "Smart Move",
        techStack: ["Flutter", "Firebase", "Google Maps"],
        width: 450,
        height: 350,
        path: "MobileApps/SmartMove",
        description: "Mobile app solving USM bus issues and traffic congestion by monitoring bus stop crowdedness and optimizing routes. Top 10 KitaHack Finalist 2025.",
        demoLink: "https://smart-move-2e56d.web.app/",
    },
    {
        id:3,
        title:"MobileApps",
        image:"/Kita_tongtong.jpg",
        category: "Kita Tongtong",
        techStack: ["Flutter", "Firebase", "Node JS", "Python"],
        description: "Financial aid mobile app with voucher-based rewards system to reduce fund misuse. Collaborated with MADAD client.",
        width: 450,
        height: 350,
        path: "Database/SportPHP",
        demoLink: "https://kita-tongtong-8cda4.web.app/",
    },
    {
        id:4,
        title:"Database",
        image:"/database.gif",
        category: "Sport Website",
        techStack: ["PHP", "MySQL", "Heroku"],
        description: "School sports registration database system built with LAMP stack.",
        width: 450,
        height: 350,
        path: "Database/SportPHP",
        demoLink: "https://sport-reg.de.r.appspot.com/pengguna_daftar.php",
    }
]