export const portfolioGallery = [
    {
        id:1,
        title:"MobileApps",
        image:"/Smart Move Vid.gif",
        category: "Smart Move",
        techStack: ["Flutter", "Firebase", "Google Maps"],
        width: 450,
        height: 350,
        path: "MobileApps/SmartMove",
        description: "This project is real world problem that I felt as a student.",
        demoLink: "https://smart-move-2e56d.web.app/",
    },
    {
        id:2,
        title:"MobileApps",
        image:"/Kita_tongtong.jpg",
        category: "Kita Tongtong",
        techStack: ["Flutter", "Firebase", "Node JS", "Python"],
        description: "This project is for my FYP.",
        width: 450,
        height: 350,
        path: "Database/SportPHP",
        demoLink: "https://kita-tongtong-8cda4.web.app/",
    },
    {
        id:3,
        title:"Database",
        image:"/database.gif",
        category: "Sport Website",
        techStack: ["PHP", "MySQL", "Heroku"],
        description: "This project showcases my expertise in building apps that run across multiple platforms using a single codebase.",
        width: 450, 
        height: 350,
        path: "Database/SportPHP",
        demoLink: "https://sport-reg.de.r.appspot.com/pengguna_daftar.php",
    }
]