export const portfolioGallery = [
    {
        id:1,
        title:"MobileApps",
        image:"/Smart Move Vid.gif",
        category: "Smart Move",
        width: 450,
        height: 350,
        path: "MobileApps/SmartMove",
        demoLink: "/demo/cross-platform",
    },
    {
        id:2,
        title:"Database",
        image:"/database.gif",
        category: "Sport Website",
        description: "This project showcases my expertise in building apps that run across multiple platforms using a single codebase.",
        width: 450,
        height: 350,
        path: "Database/SportPHP",
        demoLink: "https://pendaftaran-acara-intan-4191c8bdad3f.herokuapp.com/",
    },
    {
        id:3,
        title:"UI",
        image:"/database.gif",
        category: "Sports Website",
        width: 450,
        height: 350,
        path: "/about/Database",
        demoLink: "/demo/cross-platform",
    },
    {
        id:4,
        title:"DevOps and Cloud",
        image:"/database.gif",
        category: "Sports Website",
        width: 450,
        height: 350,
        path: "/about/Database",
        demoLink: "/demo/cross-platform",
    },
    {
        id:5,
        title:"Data Analytics, AI and ML",
        image:"/database.gif",
        category: "Sports Website",
        width: 450,
        height: 350,
        path: "/about/Database",
        demoLink: "/demo/cross-platform",
    }
]